AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - EventBridge to Step Functions

Resources:
  EC2StateWatcher:
    Type: AWS::Serverless::StateMachine
    Properties:
   
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - logs:*
            Resource: "*"
      Definition:
        StartAt: What Happened?
        States:
         
          What Happened?:
            Type: Choice
            Choices:
              - Variable: $.state
                StringEquals: running
                Next: It's Running
              - Variable: $.state
                StringEquals: stopped
                Next: It's Stopped
              - Variable: $.state
                StringEquals: terminated
                Next: It's Gone
         
          It's Running:
            Type: Pass
            End: true
          It's Stopped:
            Type: Pass
            End: true
          It's Gone:
            Type: Pass
            End: true
      Events:
        StateChange:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            InputPath: $.detail
            Pattern:
              source:
                - aws.ec2
              detail:
                state:
                  - running
                  - stopped
                  - terminated
